<!--
SPDX-FileCopyrightText: 2017-2026 TRUMPF Laser SE

SPDX-License-Identifier: MPL-2.0
-->

<Project>

  <PropertyGroup>
    <ParentDirectoryBuildProps>$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\\'))</ParentDirectoryBuildProps>
  </PropertyGroup>

  <Import Project="$(ParentDirectoryBuildProps)" Condition="'$(ParentDirectoryBuildProps)' != ''" />

  <PropertyGroup>
    <Copyright>Copyright 2017-2020 (c) TRUMPF Laser SE</Copyright>
    <Product>Service Application Framework</Product>
    <Authors>TRUMPF Laser SE</Authors>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
  </PropertyGroup>

</Project>