<!--
SPDX-FileCopyrightText: 2017-2026 TRUMPF Laser SE

SPDX-License-Identifier: MPL-2.0
-->

<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <CurrentYear>$([System.DateTime]::Now.Year)</CurrentYear>
    <Copyright>Copyright ©2017-$(CurrentYear) TRUMPF Laser SE</Copyright>
    <Product>Smart Application Framework</Product>
    <Authors>TRUMPF Laser SE</Authors>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>

</Project>