<!--
SPDX-FileCopyrightText: 2017-2026 TRUMPF Laser SE

SPDX-License-Identifier: MPL-2.0
-->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Smart Application Framework (SAF) pub/sub communication basics.</Description>
  </PropertyGroup>

  <PropertyGroup>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SAF.Communication.PubSub.Interfaces\SAF.Communication.PubSub.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
