<!--
SPDX-FileCopyrightText: 2026 TRUMPF Laser SE

SPDX-License-Identifier: LicenseRef-TRUMPF
-->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestPlugin.PublicDependencyA\TestPlugin.PublicDependencyA.csproj" />
  </ItemGroup>

</Project>
