<!--
SPDX-FileCopyrightText: 2017-2026 TRUMPF Laser SE

SPDX-License-Identifier: MPL-2.0
-->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="test-plugin-configs\settings.Environment.json" />
    <None Remove="test-plugin-configs\settings.json" />
    <None Remove="test-plugins\root.exclude.txt" />
    <None Remove="test-plugins\root.include.txt" />
    <None Remove="test-plugins\subdir\subdir.exclude.txt" />
    <None Remove="test-plugins\subdir\subdir.include.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="test-plugin-configs\settings.Environment.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="test-plugin-configs\settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="test-plugins\root.exclude.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="test-plugins\root.include.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="test-plugins\subdir\subdir.exclude.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="test-plugins\subdir\subdir.include.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Testably.Abstractions" />
    <PackageReference Include="Testably.Abstractions.Testing" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="MartinCostello.Logging.XUnit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestPlugins\TestPlugin.PluginA\TestPlugin.PluginA.csproj">
      <Private>False</Private>
      <CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
      <ExcludeAssets>all</ExcludeAssets>
    </ProjectReference>
    <ProjectReference Include="..\TestPlugins\TestPlugin.PluginB\TestPlugin.PluginB.csproj">
      <Private>False</Private>
      <CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
      <ExcludeAssets>all</ExcludeAssets>
    </ProjectReference>
    <ProjectReference Include="..\TestPlugins\TestPlugin.PublicDependencyA\TestPlugin.PublicDependencyA.csproj" />
    <ProjectReference Include="..\SAF.PluginSystem.Hosting.Extensions\SAF.PluginSystem.Hosting.Extensions.csproj" />
    <ProjectReference Include="..\SAF.PluginSystem.Hosting\SAF.PluginSystem.Hosting.csproj" />
  </ItemGroup>

  <Target Name="CopyPluginOutputs" AfterTargets="Build">
    <ItemGroup>
      <PluginAOutputFiles Include="..\TestPlugins\TestPlugin.PluginA\bin\$(Configuration)\$(TargetFramework)\**\*.*" />
      <PluginBOutputFiles Include="..\TestPlugins\TestPlugin.PluginB\bin\$(Configuration)\$(TargetFramework)\**\*.*" />
    </ItemGroup>

    <Copy SourceFiles="@(PluginAOutputFiles)" DestinationFolder="$(OutputPath)plugins\TestPlugin.PluginA\%(RecursiveDir)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(PluginBOutputFiles)" DestinationFolder="$(OutputPath)plugins\TestPlugin.PluginB\%(RecursiveDir)" SkipUnchangedFiles="true" />
  </Target>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
