name: .NET Core

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install REUSE
      run: |
        python -m pip install --upgrade pip
        pip install reuse
        
    - name: REUSE Compliance Check
      run: |
        reuse lint
        
    - name: Setup .NET Core 2.2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402
        
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: .net SxS
      run: |
        rsync -a ${DOTNET_ROOT/3.1.101/2.2.402}/* $DOTNET_ROOT/
      
    - name: Install dependencies
      run: dotnet restore './src/SmartApplicationFramework.sln'
    - name: Build
      run: dotnet build './src/SmartApplicationFramework.sln' --configuration Release --no-restore
    - name: Test
      run: dotnet test './src/SmartApplicationFramework.sln' --configuration Release --no-build --verbosity normal
    - name: Pack
      run: |
        mkdir -p ./artifacts
        dotnet pack './src/SmartApplicationFramework.sln' --configuration Release --no-build --output './artifacts'
      
    